#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TrackArtist=`osascript -e 'tell application "Spotify" to artist of current track as string'`
TrackTitle=`osascript -e 'tell application "Spotify" to name of current track as string'`

python3 "$DIR/lyrics.py" "${TrackArtist}" "${TrackTitle}" | less
